/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ambulance_car_-_low_poly.glb 
Author: Jasmin Daniel (https://sketchfab.com/jasmin.daniel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ambulance-car-low-poly-25392b75045946f7a4c9a03e3bea969e
Title: AMBULANCE CAR - LOW POLY
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AmbulanceCar(props) {
  const { nodes, materials } = useGLTF('/models/service/ambulance_car_-_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.MAT_ambulance} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/service/ambulance_car_-_low_poly.glb')
