/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blood_pack.glb 
Author: eeror (https://sketchfab.com/eeror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blood-pack-97cdde92037c4ece8a08bae4dc27526e
Title: Blood Pack
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BloodPack(props) {
  const { nodes, materials } = useGLTF('/models/service/blood_pack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kit_CuteKit_SpecialMat_0.geometry} material={materials.CuteKit_SpecialMat} />
      <mesh geometry={nodes.Kit_CuteKit_Albedo_0.geometry} material={materials.CuteKit_Albedo} />
    </group>
  )
}

useGLTF.preload('/models/service/blood_pack.glb')
