/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fire_station.glb 
Author: Paper-City (https://sketchfab.com/Paper-City)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fire-station-3c9c9bad7791465798634c6a2d465c54
Title: Fire Station
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function FireStation(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/service/fire_station.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ffe3c4d4287c4caa91917701269f94a9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Empty" position={[1692.846, 0, 1197.247]} rotation={[-Math.PI / 2, 0, -0.057]} scale={2363.062}>
                  <group name="Floor" scale={4.26}>
                    <mesh name="Floor_1_0" geometry={nodes.Floor_1_0.geometry} material={materials.material} />
                    <mesh name="Floor_solidify_0" geometry={nodes.Floor_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="house_1" position={[-0.619, 0.387, 0]} scale={0.042}>
                    <mesh name="house_1_2_0" geometry={nodes.house_1_2_0.geometry} material={materials.material_2} />
                  </group>
                  <group name="tower" position={[0.027, 0.327, 0]} scale={0.042}>
                    <mesh name="tower_solidify_0" geometry={nodes.tower_solidify_0.geometry} material={materials.solidify} />
                    <mesh name="tower_3_0" geometry={nodes.tower_3_0.geometry} material={materials.material_3} />
                    <mesh name="tower_2_0" geometry={nodes.tower_2_0.geometry} material={materials.material_2} />
                    <mesh name="tower_4_0" geometry={nodes.tower_4_0.geometry} material={materials.material_4} />
                  </group>
                  <group name="house_1001" position={[-0.619, 0.387, 0]} scale={0.042}>
                    <mesh name="house_1001_4_0" geometry={nodes.house_1001_4_0.geometry} material={materials.material_4} />
                    <mesh name="house_1001_solidify_0" geometry={nodes.house_1001_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="tower001" position={[0.027, 0.327, 0]} scale={0.042}>
                    <mesh name="tower001_3_0" geometry={nodes.tower001_3_0.geometry} material={materials.material_3} />
                  </group>
                  <group name="tower002" position={[0.027, 0.327, 0]} scale={0.042}>
                    <mesh name="tower002_4_0" geometry={nodes.tower002_4_0.geometry} material={materials.material_4} />
                    <mesh name="tower002_solidify_0" geometry={nodes.tower002_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve001" position={[0.617, -0.12, 0.002]} rotation={[Math.PI / 2, 0.676, -Math.PI / 2]} scale={0.042}>
                    <mesh name="Curve001_3_0" geometry={nodes.Curve001_3_0.geometry} material={materials.material_3} />
                    <mesh name="Curve001_solidify_0" geometry={nodes.Curve001_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve000" position={[-0.551, -0.138, 0.002]} rotation={[Math.PI / 2, 1.048, 0]} scale={0.042}>
                    <mesh name="Curve000_3_0" geometry={nodes.Curve000_3_0.geometry} material={materials.material_3} />
                    <mesh name="Curve000_solidify_0" geometry={nodes.Curve000_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve002" position={[-0.049, -0.239, 0.002]} rotation={[Math.PI / 2, 0.813, 0]} scale={0.042}>
                    <mesh name="Curve002_3_0" geometry={nodes.Curve002_3_0.geometry} material={materials.material_3} />
                    <mesh name="Curve002_solidify_0" geometry={nodes.Curve002_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve004" position={[0.144, -0.293, 0.002]} rotation={[Math.PI / 2, 0.985, 0]} scale={0.042}>
                    <mesh name="Curve004_3_0" geometry={nodes.Curve004_3_0.geometry} material={materials.material_3} />
                    <mesh name="Curve004_solidify_0" geometry={nodes.Curve004_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve003" position={[0.201, -0.05, 0.002]} rotation={[Math.PI / 2, 0.653, 0]} scale={0.042}>
                    <mesh name="Curve003_4_0" geometry={nodes.Curve003_4_0.geometry} material={materials.material_4} />
                    <mesh name="Curve003_solidify_0" geometry={nodes.Curve003_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve005" position={[0.436, -0.393, 0.002]} rotation={[Math.PI / 2, 0.941, 0]} scale={0.042}>
                    <mesh name="Curve005_4_0" geometry={nodes.Curve005_4_0.geometry} material={materials.material_4} />
                    <mesh name="Curve005_solidify_0" geometry={nodes.Curve005_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve006" position={[-0.251, -0.238, 0.002]} rotation={[Math.PI / 2, 0.787, 0]} scale={0.042}>
                    <mesh name="Curve006_4_0" geometry={nodes.Curve006_4_0.geometry} material={materials.material_4} />
                    <mesh name="Curve006_solidify_0" geometry={nodes.Curve006_solidify_0.geometry} material={materials.solidify} />
                  </group>
                  <group name="Curve007" position={[0.479, 0.077, 0.002]} rotation={[Math.PI / 2, 0.616, -Math.PI / 2]} scale={0.046}>
                    <mesh name="Curve007_4_0" geometry={nodes.Curve007_4_0.geometry} material={materials.material_4} />
                    <mesh name="Curve007_solidify_0" geometry={nodes.Curve007_solidify_0.geometry} material={materials.solidify} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/service/fire_station.glb')
