/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fire_truck_low.glb 
Author: codexito (https://sketchfab.com/codexito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fire-truck-e0fadd42bd3b448eaa0eb660764c170a
Title: Fire Truck
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FireVechicle(props) {
  const { nodes, materials } = useGLTF('/models/service/fire_truck_low.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 9.816, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 15.064, -9.811]}>
          <mesh geometry={nodes.camion_bomberos_bomberbase_0.geometry} material={materials.bomberbase} />
          <mesh geometry={nodes.camion_bomberos_bombllanta_0.geometry} material={materials.bombllanta} />
          <mesh geometry={nodes.camion_bomberos_bombruedafron_0.geometry} material={materials.bombruedafron} />
          <mesh geometry={nodes.camion_bomberos_bomruedaback_0.geometry} material={materials.bomruedaback} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/service/fire_truck_low.glb')
