/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stylized_police_station_lowpoly.glb 
Author: kartr (https://sketchfab.com/kartr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-police-station-lowpoly-92a79af1e546478abc67b07f59ded957
Title: Stylized police station lowpoly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PoliceStation(props) {
  const { nodes, materials } = useGLTF('/models/service/stylized_police_station_lowpoly.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.5, 0]} scale={1.5}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.MainWalls} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.DarkBlue} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Window} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Door} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.DarkWall} />
      </group>
      <group position={[-1.377, 3.504, -0.008]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.MainWalls} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.WhiteBlue} />
      </group>
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} position={[0.513, 3.031, -4.09]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.57} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Black} position={[-0.124, 1.555, -4.92]} scale={[0.02, 0.3, 0.02]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Black} position={[-0.124, 0.733, -4.92]} scale={[0.02, 0.3, 0.02]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Black} position={[-0.124, 2.498, -4.92]} scale={[0.02, 0.3, 0.02]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Black} position={[-2.832, 2.498, -4.92]} scale={[0.02, 0.3, 0.02]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Black} position={[-2.832, 1.523, -4.92]} scale={[0.02, 0.3, 0.02]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Black} position={[-2.832, 0.685, -4.92]} scale={[0.02, 0.3, 0.02]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.WhiteBlue} position={[-1.167, 3.528, 0.291]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Plane} position={[-2.628, -0.086, -2.796]} scale={[4.5, 0.1, 6]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.material_0} position={[-2.851, 3.086, 1.569]} rotation={[Math.PI / 2, 0, 0]} scale={0.606} />
    </group>
  )
}

useGLTF.preload('/models/service/stylized_police_station_lowpoly.glb')
